name: Compile and Deploy to GitHub Page

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ref: refs/heads/source

    - uses: actions/setup-node@v1
      with:
        node_version: '12.x'

    - name: Compile and deploy blog
      run: |
          git config --global user.email "gong_chen@qq.com"
          git config --global user.name "gong chen"
          npm i -g hexo-cli
          npm i
          npm install hexo-renderer-jade hexo-renderer-stylus --save
          sh deploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
