name: Compile and Deploy to GitHub Page

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ref: refs/heads/source

    - uses: actions/setup-node@v1
      with:
        node_version: '12.x'

    - name: Compile and deploy blog
      run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "gong_chen@qq.com"
          git config --global user.name "gonchen"
          npm i -g hexo-cli
          npm i
          npm install hexo-renderer-jade hexo-renderer-stylus --save
          hexo g
          hexo d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_ACTION_DEPLOY_KEY: ${{secrets.GH_ACTION_DEPLOY_KEY}}
